# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: maku-boot
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  banner:
    image:
      width: 120
      height: 60

#storage:
#  enabled: true
#  config:
#    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
#    type: local
#    domain: http://localhost:8080
#  local:
#    path: D://upload
#
storage:
  enabled: true
  config:
    type: aliyun
    domain: https://wangkaiblog.oss-cn-beijing.aliyuncs.com/
    prefix:
  aliyun:
    access-key-id: LTAI5tEBzsLGhN8UhhBbmUMX
    access-key-secret: uAoGhpsfneQPhVODy0wcthIOEIXcHf
    bucket-name: wangkaiblog
    end-point: oss-cn-beijing.aliyuncs.com


maku:
  xss:
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: net.maku.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
